name: demo workflow
on: workflow_dispatch
jobs:
  demo: 
    name: demo job
    runs-on: ubuntu-latest
    steps: 
    - name: Greeting
      run: |
        echo "hello"
    - name: list file
      run: ls
    - name: read file
      run: cat package.json
