name: demo workflow
on: 
  push:
    branches:
    - main
    - features/*
  pull_request:
    branches:
    - main
jobs:
  demo: 
    name: demo job
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v6.0.1

    - name: Setup Node.js environment
      uses: actions/setup-node@v6.1.0
      with: 
        node-version: 16.x

    - name: Cache
      uses: actions/cache@v5.0.1
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/.npm
              node_module
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      
      
    # - name: set nodejs
    #   run: |
    #     curl -s https://deb.nodesource.com/setup_16.x | sudo bash
    #     sudo apt install nodejs -y
    - name: instal dependency
      run: |
        npm install

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v6.0.0
      with:
        # Artifact name
        name: build-{{ GITHUB.RUN_ID }}
        # A file, directory or wildcard pattern that describes what to upload
        path: build/
        # The desired behavior if no files are found using the provided path.
   

      




        
    - name: set build
      run: |
          npm run build
