name: demo workflow
on: 
  push:
    branches:
    - main
    - features/*
  pull_request:
    branches:
    - main
jobs:
  demo: 
    name: demo job
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v6.0.1
    - name: Greeting
      run: |
        echo "hi"
    - name: list file
      run: ls
    - name: read file
      run: cat package.json
